language: python

python:
- '3.8'

services:
- docker

before_install:
- pip install docker-compose coverage
- pip install -r requirements.txt

script:
- make test_docker
- make test
- bash <(curl -s https://codecov.io/bash)
